default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default

queue:
  <<: *default

cable:
  <<: *default

cache:
  <<: *default
