default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
  public_url: <%= ENV['DATABASE_PUBLIC_URL'] %>
  database: <%= ENV['PGDATABASE'] %>
  host: <%= ENV['PGHOST'] %>
  username: postgres
  password: <%= ENV['PGPASSWORD'] %>
  port: <%= ENV['PGPORT'] %>

production: 
  <<: *default

development: 
  <<: *default

test:
  <<: *default

queue:
  <<: *default

cable:
  <<: *default

cache:
  <<: *default
