default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Ensure DATABASE_URL is always used

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

queue:
  <<: *default
cable:
 <<: *default