production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
development:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
cable:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
queue:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
cache:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 