production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
cable:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
queue:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL
cache:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>  # ✅ Always use DATABASE_URL